name: first website for cloud
'on':
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      - name: Configure AWS Credentials
        uses: jakejarvis/s3-sync-action@master
        with:
          args: '--follow-symlinks --delete'
        env:
          AWS_S3_BUCKET: '${{ secrets.AWS_S3_BUCKET }}'
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          SOURCE_DIR: index.html
          aws-region: us-east-1
