name: first website for cloud
'on':
  push:
    branches:
      - master
jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1  # Official AWS Action for credentials
        with:
          aws-access-key-id: '${{ secrets.AWS_ACCESS_KEY_ID }}'
          aws-secret-access-key: '${{ secrets.AWS_SECRET_ACCESS_KEY }}'
          aws-region: 'us-east-1'

      - name: Sync files to S3
        run: |
          aws s3 sync ./ s3://${{ secrets.AWS_S3_BUCKET }}/ --follow-symlinks --delete
        env:
          SOURCE_DIR: ./  # Specify the sour